### ISSUE TITLE
Request for checkpoint file

### ISSUE THREAD

**Issue by zuoxingdong** [mqtlam/dcgan-tfslim#1]
Could you help to upload a checkpoint file, so that we can play with it easily without training on CPU which is too slow to train.

**Comment by themichaellam** [comment]
I've added a branch called demo that contains a sample celebA checkpoint: https://github.com/mqtlam/dcgan-tfslim/tree/demo/checkpoint_demo  I hope this is helpful.

Unfortunately, there seems to be a bug in loading a checkpoint to resume training.  See issue #2.

In addition, I haven't implemented any visualization capabilities such as visualizing generated images.  I've been using TensorBoard but one can implement more powerful visualization capabilities.  If I have time, I may add some code to save generated images.
